# This file ensures the generated_tools directory is treated as a Python package
"""
Generated tools directory for Prometheus 2.0

This directory contains dynamically created tools generated by the agent
during its self-improvement process.
"""
