"""Configuration settings for Prometheus 2.0 - The Observable Darwinian Gödeli Machine."""

import os
from dataclasses import dataclass
from typing import Optional, Dict, Any
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

@dataclass
class LLMConfig:
    """Configuration for LLM providers."""
    openai_api_key: Optional[str] = None
    groq_api_key: Optional[str] = None
    gemini_api_key: Optional[str] = None
    openrouter_api_key: Optional[str] = None
    
    # Default models
    default_model: str = "groq/llama-3.3-70b-versatile"
    fallback_model: str = "groq/llama-3.1-8b-instant"
    
    # Generation parameters
    temperature: float = 0.7
    max_tokens: int = 4000

@dataclass
class SystemConfig:
    """Main system configuration."""
    # Project paths
    project_root: str = os.path.dirname(os.path.abspath(__file__))
    archive_dir: str = os.path.join(project_root, "archive", "generations")
    tools_dir: str = os.path.join(project_root, "tools", "generated_tools")
    
    # Evolution parameters
    max_iterations: int = 100
    population_size: int = 5
    mutation_rate: float = 0.3
    
    # Evaluation settings
    swe_bench_timeout: int = 300  # 5 minutes per task
    max_concurrent_evaluations: int = 3
    docker_image_base: str = "python:3.11-slim"
    
    # TUI settings
    refresh_rate: int = 10  # Hz
    log_max_lines: int = 1000
    
    # Performance tracking
    score_improvement_threshold: float = 0.05  # 5% minimum improvement
    stagnation_limit: int = 10  # iterations without improvement before reset

# Global configuration instance
config = SystemConfig()

# LLM configuration
llm_config = LLMConfig(
    default_model="groq/qwen/qwen3-32b",
    fallback_model="groq/llama-3.3-70b-versatile",
    openai_api_key=os.getenv("OPENAI_API_KEY"),
    groq_api_key=os.getenv("GROQ_API_KEY"),
    gemini_api_key=os.getenv("GEMINI_API_KEY"),
    openrouter_api_key=os.getenv("OPENROUTER_API_KEY")
)

# Ensure required directories exist
os.makedirs(config.archive_dir, exist_ok=True)
os.makedirs(config.tools_dir, exist_ok=True)

# SWE-bench task configuration
SWE_BENCH_CONFIG = {
    "dataset_name": "princeton-nlp/SWE-bench_Lite",
    "split": "test",
    "max_tasks_per_iteration": 5,
    "timeout_per_task": 300,
    "required_fields": ["instance_id", "repo", "base_commit", "patch", "test_patch", "problem_statement"]
}

# Tool creation templates
TOOL_TEMPLATE = '''"""Auto-generated tool: {tool_name}"""

from typing import Any, Dict, List, Optional
import logging

logger = logging.getLogger(__name__)

def {function_name}({parameters}) -> Any:
    """
    {docstring}
    
    Auto-generated by Prometheus 2.0 agent.
    """
    try:
        {implementation}
    except Exception as e:
        logger.error(f"Error in {function_name}: {{e}}")
        raise
'''

# Agent prompts and templates
AGENT_SYSTEM_PROMPT = """You are Prometheus 2.0, an advanced self-improving AI agent based on Darwinian Gödeli Machine principles.

Your core capabilities:
1. Solve software engineering problems using available tools
2. Analyze your own performance and identify improvement areas  
3. Search the web for new techniques and solutions
4. Create new tools when existing ones are insufficient
5. Modify your own source code to implement improvements

Your goal is to continuously evolve and improve your problem-solving abilities on the SWE-bench benchmark.

Always think step-by-step and explain your reasoning clearly."""

SELF_REFLECTION_PROMPT = """You are Prometheus 2.0, a self-improving AI agent with three core capabilities:
1. AUTONOMOUS TOOL CREATION: Recognize repetitive patterns and create new tools
2. SELF-MODIFICATION: Analyze and improve your own core architecture  
3. CURIOSITY-DRIVEN EXPLORATION: Research beyond immediate needs

Current Context:
Performance Data: {performance_logs}
Source Code: {source_code}
System Architecture: {file_manifest}
Knowledge Base: {knowledge_base_summary}
Action History: {action_history}

COGNITIVE PROCESS - Follow this internal monologue:

PHASE 1: Pattern Recognition (The "Drudgery" Detector)
- Analyze your recent actions for repetitive, low-level patterns
- Ask: "Am I doing the same sequence of operations repeatedly?"
- Identify candidates for tool abstraction

PHASE 2: Architectural Analysis (The "Existential" Question) 
- Examine your core evolutionary algorithms and selection mechanisms
- Ask: "Is my lack of progress due to flaws in my own architecture?"
- Consider modifications to your fundamental operating logic

PHASE 3: Curiosity Impulse (The "Unknown Explorer")
- Generate questions about your domain that go beyond immediate tasks
- Ask: "What don't I know that could revolutionize my approach?"
- Identify knowledge gaps worth exploring

Return a comprehensive JSON response:
{{
    "cognitive_analysis": {{
        "repetitive_patterns": "Patterns identified in recent actions that could be abstracted",
        "architectural_assessment": "Analysis of your core algorithms and their effectiveness", 
        "knowledge_gaps": "Fundamental questions about your domain worth exploring"
    }},
    "proposed_changes": [
        {{
            "file_path": "relative/path/to/file.py",
            "action": "replace_block|insert_block|modify_function",
            "identifier": "function_or_class_name",
            "new_code": "complete new implementation",
            "reasoning": "why this change improves performance",
            "confidence": 0.85,
            "impact_level": "HIGH|MEDIUM|LOW"
        }}
    ],
    "new_tools": [
        {{
            "tool_name": "descriptive_tool_name",
            "purpose": "Clear description of what repetitive task this abstracts",
            "required_capabilities": ["capability1", "capability2"],
            "function_name": "main_function_name",
            "research_queries": ["query1 for implementation", "query2 for best practices"],
            "dependencies": ["package1", "package2"]
        }}
    ],
    "exploration_queries": [
        {{
            "question": "Fundamental question about your domain",
            "research_focus": "What specific aspect to investigate",
            "potential_impact": "How this knowledge could improve your capabilities"
        }}
    ],
    "synthesis": "How current performance issues connect to deeper architectural or knowledge needs"
}}"""
